### ISSUE TITLE
Need a hardware add-on for the Pi 0 to interface with phone

### ISSUE THREAD

**Issue by mo-g** [mo-g/1910calleditwantsitsphoneback#12]
[Fe-Pi pinout](https://pinout.xyz/pinout/audio_z#)

[Using PWM1 on BCM13 for mono sound out](https://learn.adafruit.com/introducing-the-raspberry-pi-zero/audio-outputs)

So, this project needs two audio outputs and one audio input. One of each is provided by the Fe-Pi board, which means that there's a need for at least one more output using the Pi's own hardware. This is made slightly trickier since we're using a Pi 0, which has no analogue audio hardware. The adafruit article shows how to use two GPIO pins and some components to recreate the audio circuitry from the original Pi. I will also need to add amplifiers for the speaker and probably the transducers, so that could be part of the same circuit. The ideal would be that I build a baseboard for the 0W which mounts with headers, and connects everything but the Fe-Pi with a single plug.

That needs to be built!

**Comment by mo-g** [comment]
I have the pinouts mapped and saved in the current branch's README.md. I also have some stacking headers for the 0W that will allow me to mount it on a board, and then mount the Fe-Pi at the top of the stack. I could also consider reversing that, mounting the Fe-Pi under the 0W so I can use header pins for a single-connection solution, but unfortunately it looks like they aren't aligned with the 40pin's grid, which means they'll be off-axis from a protoboard, and using a cable will be necessary.

**Comment by enishoca** [comment]
you need to have the flexibility of using both at the same time.  I had to make a change where you initialize alsa - you were assuming different plugs for each.  I had to put a conditional in to address that.  BTW you haven't update since Nov are you still working on this project?  seems like a couple  changes from the branch need to ported back in.
I am using this on an ericofon and your astral mappings matched exactly how I had wired my pi, minus output leds don't have any use for them.    Don't have the software fully working yet. But I have so far gotten to the point of daemon staring without errors.

**Comment by mo-g** [comment]
Woah, holy crap. Sorry! I didn't realise you'd commented. Hi!

You're right, I've been distracted with other projects, but I was digging out my notes on the weekend with a mind to finishing this up. Are *you* still working on this? :laughing:
