### ISSUE TITLE
Program is aborted on incoming call

### ISSUE THREAD

**Issue by enishoca** [mo-g/1910calleditwantsitsphoneback#19]
When I lift the handset call is aborted with a from pjsip

[INFO] Handset lifted.
python: ../src/pj/os_core_unix.c:692: pj_thread_this: Assertion `!"Calling pjlib from unknown/external thread. You must " "register external threads with pj_thread_register() " "before calling any pjlib functions."' failed.
Aborted

**Comment by mo-g** [comment]
I never actually got this far! The point I was at was to start prototyping my hardware set-up. Are you also using a Fe-Pi as your audio interface?

**Comment by mo-g** [comment]
Hey @enishoca, I've been working today - got a fresh raspbian card running, tested audio-out on the earpiece, and microphone line-in. Looks like I'll need to build a pre-amplifier for that, so I need to get hold of some LM358's next week for that job.

My current plan is to use an LM386 amp for a speaker driver for the pi's internal audio to use as a ringer, the LM358 for the mouthpiece, and connect the earpiece directly to the Fe-Pi's line out - that last of which seems to work pretty well so far.

I'll have a look at trying to test the dialling mechanism. I'm assuming I should be using in-line resistors to prevent surges on the GPIO lines. I want this thing finished!

If I recall correctly, where I paused last time - I needed to compile a more recent build of pjsip, because the repository version was borked. I'll make that a job for tomorrow.
